# will be docs.publishing.service.gov.uk
host: https://govuk-tech-docs.herokuapp.com/
service_link: /

show_govuk_logo: true
service_name: Developer docs

header_links:
  Dashboard: /
  Publishing API: /apis/publishing-api.html
  Search API: /apis/search-api.html
