- name: "Applications"
  sections:
    - name: Publisher applications
      repos:
        - collections-publisher
        - contacts-admin
        - content-tagger
        - hmrc-manuals-api
        - maslow
        - panopticon
        - policy-publisher
        - publisher
        - short-url-manager
        - specialist-publisher
        - travel-advice-publisher
        - whitehall

    - name: APIs
      repos:
        - content-store
        - email-alert-api
        - email-alert-service
        - govuk_content_api
        - govuk_need_api
        - imminence
        - publishing-api
        - rummager

    - name: Infrastructure
      repos:
        - router
        - router-api

    - name: Utility apps
      repos:
        - search-admin
        - signonotron2
        - recommended-links
      sites:
        - name: gds/router-data
          url: https://github.gds/gds/router-data
          description: Send routes directly to the router-api (deprecated)

    - name: Support
      repos:
        - support
        - support-api

- name: Front end applications
  sections:
    - name: Frontend Applications
      repos:
        - business-support-finder
        - calculators
        - calendars
        - collections
        - contacts-frontend
        - design-principles
        - email-alert-frontend
        - feedback
        - finder-frontend
        - frontend
        - government-frontend
        - info-frontend
        - licence-finder
        - manuals-frontend
        - multipage-frontend
        - smart-answers
        - specialist-frontend
        - whitehall

    - name: For assets
      repos:
        - asset-manager
        - static

- name: Developing
  sections:
    - name: Starting a project
      repos:
        - govuk-rails-app-template
        - govuk_admin_template
        - govuk_prototype_kit

    - name: Running on the VM
      sites:
        - name: gds/development
          url: https://github.gds/gds/development
          description: Tools to run GOV.UK apps in the VM

      repos:
        - gds-boxen

    - name: Testing
      repos:
        - govuk-content-schemas
        - govuk-content-schema-test-helpers

    - name: Gems &amp; Libraries
      repos:
        - gds-api-adapters
        - govuk_message_queue_consumer
        - govuk_content_models
        - gds-sso
        - govspeak
        - plek
        - slimmer

    - name: Quality
      repos:
        - govuk_security_audit
        - govuk-lint
        - styleguides

    - name: Frontend libraries
      repos:
        - govuk-component-guide
        - govuk_template
        - govuk_elements
        - govuk_frontend_toolkit
        - govuk_frontend_toolkit_gem
        - govuk_frontend_toolkit_npm
